ebaApp/urls.py
from django.contrib import admin
from django.urls import path,include

from story8.views import fungsi_data

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story3.urls')),
    path('story1', include('home.urls')),
    path('story6',include('story6.urls')),
    path('story7',include('story7.urls')),
    path('story8',include('story8.urls')),
    path('story9',include('story9.urls')),
    path('data/', fungsi_data),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

story3/urls.py
from django.urls import path

from . import views

app_name = 'story3'

urlpatterns = [
    path('', views.index, name='index'),
    path('newindex', views.about, name="about"),
    path('index.html', views.contacts, name='contacts'),
    path('isi_form',views.isi_form, name="isi_form"),
    path('lihat_response',views.lihat_response, name="lihat_response"),
    path('delete/<int:id>', views.delete_jadwal, name='delete'),
    path('detail/<int:id>', views.lihat_detail, name='detail')
]

story6/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'story6'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('tambah/', views.add_event, name='add_event'),
    path('tambah_orang/', views.add_orang, name='add_orang'), 
]

story7/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'story7'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"), 
]

story8/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'story8'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('data/', views.fungsi_data), 
]

story9/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

app_name = 'story9'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('accounts/', include('django.contrib.auth.urls')),
]

home/models.py
from django.db import models

# Create your models here.

story3/models.py
from django.db import models

# Create your models here.

class gForm(models.Model) :
    term = models.CharField(max_length=120) #max_length = required
    subject = models.CharField(max_length=120) #max_length = required
    credit = models.CharField(max_length=120) #max_length = required
    lecturer = models.CharField(max_length=120) #max_length = required
    classroom = models.CharField(max_length=120) #max_length = required
    description = models.CharField(max_length=240) #max_length = required
    featured = models.BooleanField(default=True)
    
def __str__(self):
    return self.subject
    

story6/models.py
from django.db import models

# Create your models here.
class Acara(models.Model):
    nama_acara = models.CharField(max_length = 50)

    def __str__(self):
        return self.nama_acara

class Peserta(models.Model):
    nama = models.CharField(max_length = 30)
    acara = models.ForeignKey(Acara, on_delete=models.CASCADE, related_name = 'attendances')

    def __str__(self):
        return self.nama

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story3/forms.py
from django import forms
from .models import gForm

class SubForm(forms.ModelForm) :
    class Meta :
        model = gForm
        fields = [
            'term',
            'subject',
            'credit',
            'lecturer',
            'classroom',
            'description',
        ]

        widgets = {
                'term':forms.TextInput(attrs={'class':'form-control','placeholder':'Select your term'}),
                'subject':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your subject'}),
                'credit':forms.TextInput(attrs={'class':'form-control','placeholder':'Select your credits'}),
                'lecturer':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your Lecturer'}),
                'classroom':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your Classroom'}),
                'description':forms.Textarea(attrs={'class':'form-control','placeholder':'Please describe your subject!'}),
            }

story6/forms.py
from django import forms
from .models import Acara,Peserta

class FormAcara(forms.ModelForm):
    class Meta :
        model = Acara
        fields = ('nama_acara',)

class FormPeserta(forms.ModelForm) :
    class Meta :
        model = Peserta
        fields = ('nama',)

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'home/index.html')

story3/views.py
from django.shortcuts import (render,redirect)
from django.http import HttpResponseRedirect
from .forms import SubForm
from .models import gForm
from . import models

# Create your views here.
def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, "newindex.html")

def contacts(request):
    return render(request, "index.html")

def isi_form(request):
    form = SubForm(request.POST or None)
    if form.is_valid() :
        form.save()
    context = {
        'form' : form
    } 
    return render(request, "form.html",context)

def lihat_response(request) :
    posts = gForm.objects.all()
    context = {
        'jadwal' : posts
    }
    return render(request, "response.html",context)

def delete_jadwal(request, id):
    gForm.objects.get(id=id).delete()
    return redirect ('/lihat_response')

def lihat_detail(request, id):
    subjek = gForm.objects.filter(id=id)
    context = {
        'subjek' : subjek
    }
    return render(request, 'detail.html', context)


story6/views.py
from django.shortcuts import render,redirect
from .forms import FormAcara, FormPeserta
from .models import Acara,Peserta

# Create your views here.
def index(request) :
    acara = Acara.objects.all()
    peserta = Peserta.objects.filter(acara=acara)
    return render(request, "story6/index.html", {
        'acara' : acara,
        'peserta' : peserta,
    })


def add_event(request) :
    if request.method == 'POST' :
        form_satu = FormAcara(request.POST)
        if form_satu.is_valid():
            form_satu.save()
            return redirect('story6:index')

    else :
        form_satu = FormAcara()
    return render(request, 'story6/add_acara.html', {
        'form_satu' : form_satu
    })
    
def add_orang(request) :
    if request.method == 'POST' :
        form_dua = FormPeserta(request.POST)
        if form_dua.is_valid():
            form_dua.save()
            return redirect('story6:index')
    else :
        form_dua = FormPeserta()
    return render(request, 'story6/add_orang.html',{
        'form_dua' : form_dua
    })

story7/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story7/index.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.
def index(request):
    return render(request, 'story8/story8.html')

def fungsi_data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret = requests.get(url)
    print(ret.content)

    data = json.loads(ret.content)
    # data = {'coba': 'ini isinya', 'sesuatu':'asdfsdf'}
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import User

# Create your views here.

def index(request):
    count = User.objects.count()
    return render(request, "story9/index.html",{
        'count' : count
    })

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('/story9accounts/login/')
    else :
        form = UserCreationForm()
    return render(request,"registration/signup.html", {
        'form' : form
    })

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Tammudu+2:wght@400;500;600;700;800&family=Epilogue:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <title>Hello</title>
</head>
<body>
  <header>
  <!-- kolom kiri -->
    <p class="hehe">
      <img src="{% static 'home/image.jpeg' %}" alt="EbaAja" style="width:170px;height:200px;margin-left:50px;" />
      <h1>hi, i'm<br/>eba(aja)</h1>
      <h4>learning how to code</br> is my daily bread</h4>
    </p>
    <div>
      <ul class="cerita">
        <li>My Student ID is 1906398875</li>
        <li>I'm an undergraduate student at Faculty of Computer Science University of Indonesia</li>
        <li>I went to Saint Thomas Elementary, Junior High, and Senior High School</li>
        <li>Well, i love to sing, even tho it cracked most of the time</li>
        <li>If you wanna know me more, hmu at anebaemiya(ig and line), </br>and we could talk it out</li>
        <a href="index.html#home">Click here to go back</a>
      </ul>
    </div>

    </header>
      <footer>
        <h2>any questions?</br>
        find me here eba.br@ui.ac.id</br>
        <ul class = "coba"> designed by eba ginting </ul>
        </h2>
      </footer>
</body>
</html>

story3/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Eba Ginting</title>

</head>
<body>

{% block content %}
{% endblock %}

</body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</html>

story3/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'navbar.html' %}

<div class="c" style="height:810px">
    <div class="col-md-12 mb-5">
    <div class="section-heading text-center mb-5">
        <h2 class="apa"> #de<span class="pink">TAIL</span><span class="royal">s.</span></h2>
    </div>
    </div>
    <table class="table table-borderless">
        <tbody>
            <thead>
                <tr class="pink">
                    <th scope="col">Term</th>
                    <td> {{subjek.term}} </td>
                </tr>
                <tr class="pink">
                    <th scope="col">Subject</th>
                    <td> {{subjek.subject}} </td>
                </tr>
                <tr class="pink">    
                    <th scope="col">Credits</th>
                    <td> {{subjek.credit}} </td>
                </tr>
                <tr class="pink"> 
                    <th scope="col">Lecturer</th>
                    <td> {{subjek.lecturer}} </td>
                </tr>
                <tr class="pink">
                    <th scope="col">ClassRoom</th>
                    <td> {{subjek.classroom}} </td>
                </tr>
                <tr class="pink">
                    <th scope="col">Description</th>
                    <td> {{subjek.description}} </td>
                </tr>
            </thead>
           
                <td> 
                    <a  href="/lihat_response"> 
                        <button type="submit" class="btn btn-outline-primary rounded-pill"> Back </button>
                    </a>
                </td>
                
        </tbody>
    </table>
</div>


{% endblock %}

story3/templates/form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'navbar.html' %}

<section class="c">
    <div class="col-md-12 mb-5">
    <div class="section-heading text-center mb-5">
        <h2 class="apa"> Fill <span class="pink">The</span> <span class="royal">FORM</span></h2>
    </div>
    </div>

    <form method = 'POST'> {% csrf_token %}
        {{form.as_p}}
        <input type = 'submit' value='SEND'/>
    </form>
    </section>

{% endblock %}

story3/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- navbar -->
    {% include 'navbar.html' %}

    <!-- bikin bagian-bagiannya -->
    <section id="home">
      <div class="a">
        <h1 class="hi hello">Welcome to a place where</br> you will explore</h1>
        <h3 class="bye hello">about someone named</h3>
      </div>
    </section>

    <section>
      <div class="b">
        <h1 class= "eba ukuran">EBA</h1>
        <h2 class= "ukuran warna1">1906398875</h2>
        <h2 class= "ukuran warna2">1906398875</h2>
        <h2 class= "ukuran warna3">1906398875</h2>
      </div>
    </section>

    <section class="c" id = "resume">
      <div class="container-sm d">
        <div class="row">

          <div class="col-md-12 mb-5">
            <div class="section-heading text-center mb-5">
              <h2 class="apa"> My <span class="royal">Resume</span></h2>
            </div>
          </div>

          <div class="col-md-6">
            <h2 class="mb-5"> Education </h2>

            <div class="resume-item mb-4">
              <h6> 2011 - 2013 </h6>
              <h4> Saint Michael <span class="royal"> Elementary </span> School </h4>
              <p> The first Elementary School that i went to, but i need to got out, cause My Family and I move from my old house.</p>
            </div>

            <div class="resume-item mb-4">
              <h6> 2011 - 2013 </h6>
              <h4> Saint Thomas 5 <span class="royal"> Elementary </span> School </h4>
              <p> That's actually not my first Elementary school, i am a transferred student, so yeah it was quiet hard at the first time. But i'm okay cause after all im an extrovert.</p>
            </div>


            <div class="resume-item mb-4">
              <h6> 2013 - 2016 </h6>
              <h4> Saint Thomas 1 <span class="royal">Junior</span> High School </h4>
              <p> The reason why i go to this school probally because this is one of the most famous high school in my town, so i took the test, and i'm in.</p>
            </div>


            <div class="resume-item mb-4">
              <h6> 2016 - 2019 </h6>
              <h4> Saint Thomas 1 <span class="royal">Senior</span> High School </h4>
              <p> The reason why i choose to continue going to the same school as my junior high school is probally because most of my friends go there too, and it is one of the most famous High School in my town, so i took the test(again), and i'm in. </p>
            </div>

            <div class="resume-item mb-4">
              <h6> 2019 - Present </h6>
              <h4> <span class="royal">Universitas</span> Indonesia </h4>
              <p> Tbh, sometimes it still feels like a dream. I don't know how but now i am here, taking my first ever degree in Universitas Indonesia. I thank God everyday for this opportunity, i am beyond grateful!</p>
            </div>
        </div>

          <div class="col-md-6">
            <h2 class="mb-5"> Experiences </h2>

            <div class="resume-item mb-4">
              <h6> 2019 - Present </h6>
              <h4> <span class="royal">Staff</span> of Art and Culture Department at BEM Fasilkom UI </h4>
              <p> This year, i got a job to handle Teater Biru Merah, check us out on @teaterbirumerah(ig). I actually am not good at it. </p>
            </div>

            <div class="resume-item mb-4">
              <h6> Present </h6>
              <h4> <span class="royal">Teaching Assistant</span> of Calculus 1 </h4>
              <p> This is actually surprising, that i really took the opportunity to become a Teaching Assistant, i just hope everything will be okay.</p>
            </div>

            <div class="resume-item mb-4">
              <h6> Present </h6>
              <h4> <span class="royal">Staff</span> of Liason Officer at OIM UI </h4>
              <p> Yasmin asked me to try this position so i took it, and surprisingly i passed the test.</p>
            </div>

            <div class="resume-item mb-4">
              <h6> Present </h6>
              <h4> <span class="royal">Staff</span> of Finance and Beverage at OH Fasilkom UI </h4>
              <p> Just being a staff cause i love selling things and luckily i have a super duper cool team. We actually do a really cool job, we even open a Paid Promote, bhsakakakaka</p>
            </div>

            <div class="resume-item mb-4">
              <h6> SOON </h6>
              <h4> <span class="royal">VPIC</span> Event of Educare </h4>
              <p> Please look forward for another amazing project of mine! By the way i'm in charge with one of my fav person in uni, Yasmin Zhafira.</p>
            </div>
          </div>

        </div>
      </div>
    </section>

    <section class="e" id = "hobby">
      <div class="container-sm f">
        <div class="row">

          <div class="col-md-12 mb-5">
            <div class="section-heading text-center mb-5">
              <h2 class="apa"> <span class="pink">Hobby</span> and<span class="royal"> Interest </span></h2>
            </div>
          </div>

              <div class="col-md-6">
                <div class="hobby-item-pink mb-4">
                  <h4>Singing</h4>
                  <p> I don’t have a good voice, but i love to sing just to relieve my stress, enjoy my bath, and making memories with my voice. I enjoy listening to music, and sing along to it.</p>
                </div>

                <div class="hobby-item-royal mb-4">
                  <h4>Public Speaking</h4>
                  <p>I love speaking so much. I actually can talk for hours and i don’t feel bored with it. I just have too many things to talk about, and i don’t really feel nervous when i meet new people.</p>
                </div>

                <div class="hobby-item-pink mb-4">
                  <h4>Socializing</h4>
                  <p>I love meeting new people, and i just don’t wanna miss a chance to get close with someone new. I love having a good long term relationship with anyone. I really treasure my </p>
                </div>

                <div class="hobby-item-royal mb-4">
                  <h4>Fashion</h4>
                  <p>As you can see, i don’t really have a good style or body, but i’m interested to learn more about fashion just to make me feel great about myself.</p>
                </div>
              </div>
    </section>

    <section class="w3-content w3-display-container cd" id="surp">
      <img class="mySlides" src="static/img/a.png" style="width:100%">
      <img class="mySlides" src="static/img/b.png" style="width:100%">
      <img class="mySlides" src="static/img/c.png" style="width:100%">
      <img class="mySlides" src="static/img/d.png" style="width:100%">
    </section>

    <section class="c" id="contact">
      <div class = "container-sm">
        <div class = "row">

          <div class="col-md-12 mb-5">
            <div class="section-heading text-center mb-5">
              <h2 class="apa"> <span class="royal">Get</span> <span class="pink">In Touch</span></h2>
            </div>
          </div>

          <div class="col-md-6">
            <form action="" class="site-form">
              <h3 class="mb-5 white">Leave Some <span class="royal">Mess</span>ages</h3>
              <div class="form-group">
                <input type="text" class="form-control px-3 py-4" placeholder="Your Name">
              </div>
              <div class="form-group">
                <input type="email" class="form-control px-3 py-4" placeholder="Your Email">
              </div>
              <div class="form-group">
                <input type="email" class="form-control px-3 py-4" placeholder="Your Phone">
              </div>
              <div class="form-group mb-5">
                <textarea class="form-control px-3 py-4"cols="30" rows="10" placeholder="Write a Message"></textarea>
              </div>
              <div class="form-group mb-5">
                <input type="submit" class="btn btn-outline-primary rounded-pill px-4 py-3" value="Send Message">
              </div>
            </form>
          </div>

        <div class="col-md-6">
  				<h3 class="mb-5 white">My Contact De<span class="pink">tail</span>s</h3>
  				<ul class="site-contact-details">
            <div class="row">
  						<li>
  							<h6 class="text-uppercase">Email</h6>
  							eba.br@ui.ac.id
  						</li>
            </div>
            <div class="row">
  						<li>
  							<h6 class="text-uppercase">Phone</h6>
  							+62 812 6358 0099
  						</li>
            </div>
            <div class="row">
  						<li>
  							<h6 class="text-uppercase">Line | WhatsApp</h6>
  							anebaemiya | 0812 6358 0099
  						</li>
            </div>
            <div class="row">
  						<li>
  							<h6 class="text-uppercase">Address</h6>
  							Jalan Jamin Ginting no 88, Medan, Sumatera Utara, 20141  <br>
  							or <br>
  						  Jalan Masjid Al-Farouq, Kos Puri Delima, Kukusan Beji, Depok
  						</li>
            </div>
  				</ul>
  			</div>
    </section>


    <footer class="site-footer" style="background-color:#000000;">
  		<div class="container" >

  			<div class="row mb-5">
  				<p class="col-12 text-center foot" style="font-size: 20px">
            <span class="pink">All rights reserved </span> |<span class="royal"> This website is made by EBA</span>
          </p>
        </div>

        <div class="row mb-5">
          <div class="col-md-12 text-center">
            <p>
              <!-- instagram -->
              <a href="https://www.instagram.com/anebaemiya/" class="social-item"><span class="icon back-blue"><img src="https://img.icons8.com/fluent-systems-filled/48/000000/instagram-new.png"/></span></a>

              <!-- twitter -->
              <a href="#" class="social-item"><span class="icon-twitter"><img src="https://img.icons8.com/android/48/000000/twitter.png"/></span></a>

              <!-- spotify -->
              <a href="https://open.spotify.com/user/31lvwas7bwnbiafpqqwwx7gqhlwq?si=M0C334BSR2mUqA0yiAsl7A" class="social-item"><span class="icon-instagram2"><img src="https://img.icons8.com/material-sharp/48/000000/spotify.png"/></span></a>

              <!-- linkedin -->
              <a href="https://www.linkedin.com/in/eba-ginting-3740811b6/" class="social-item"><span class="icon-linkedin2"><img src="https://img.icons8.com/fluent-systems-filled/48/000000/linkedin.png"/></span></a>

              <!-- line -->
              <a href="#" class="social-item"><span class="icon-vimeo"><img src="https://img.icons8.com/fluent-systems-filled/48/000000/chat.png"/></span></a>

            </p>
          </div>
        </div>
      </div>
    </footer>


    <script>
    var myIndex = 0;
    carousel();

    function carousel() {
      var i;
      var x = document.getElementsByClassName("mySlides");
      for (i = 0; i < x.length; i++) {
        x[i].style.display = "none";
      }
      myIndex++;
      if (myIndex > x.length) {myIndex = 1}
      x[myIndex-1].style.display = "block";
      setTimeout(carousel, 5000); // Change image every 2 seconds
    }
    </script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  {% endblock %}
</html>

story3/templates/response.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'navbar.html' %}

<section class="c" style="height:auto">
    <div class="col-md-12 mb-5">
    <div class="section-heading text-center mb-5">
        <h2 class="apa"> #res<span class="pink">PON</span><span class="royal">ses.</span></h2>
    </div>
    </div>
    <title> jadwal </title>
    <table class="table ">
            <thead>
                <tr class="pink">
                    <th scope="col">Subject</th>
                    <th scope="col">lecturer</th>
                    <th scope="col">Details</th>
                    <th scope="col" class="text-center">Delete</th>
                </tr>
            </thead>
            
            <tbody>
                {% for j in jadwal %}
                <tr class = "white">
                    <td> {{j.subject}} </td>
                    <td> {{j.lecturer}} </td>
                    <td> 
                        <a  href="{% url 'story3:detail' j.id %}​​"> 
                            <button type="submit" class="btn btn-outline-primary rounded-pill"> Details </button>
                        </a>
                    </td>
                     <td> 
                        <a  href="{% url 'story3:delete' id=j.id %}"> 
                            <button type="submit" class="btn btn-outline-primary rounded-pill"> Delete </button>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            
        </table>
</section>

{% endblock %}

story6/templates/story6/add_acara.html
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        <h1>Tambah event</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_satu.as_p }}
            <button type="submit" class="add-btn">Tambahkan acara</button>
        </form>
    </body>
</html>

story6/templates/story6/add_orang.html
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        <h1>Tambah orang</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_dua.as_p }}
            <button type="submit" class="add-btn">Tambahkan nama peserta</button>
        </form>
    </body>
</html>

story6/templates/story6/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'navbar.html' %}

<section class="c" style="height:auto">
    <div class="col-md-12 mb-5">
    <div class="section-heading text-center mb-5">
        <h2 class="apa"> #<span class="pink">STORY</span><span class="royal">6.</span></h2>
    </div>
    </div>
    {% if acara %}
    <table class="table">
        <thread>
            <tr class="pink">
                <th scope="col">Nama Acara</th>
                <th scope="col">Nama Peserta</th>
                <th scope="col">Action</th>
            </tr>
        </thread>
            
        <tbody>
        {% for n_acara in acara %}
            <tr class = "white">
                <td> {{n_acara.nama_acara}} </td>
                <td> 'halo' </td>
                <td> 
                    <a href = "{% url 'story6:add_orang'%}"> 
                        <button type="submit" class="btn btn-outline-primary rounded-pill"> Tambah Peserta </button>
                    </a>
                </td>
            </tr>
        {% endfor %}
            {% else %}
                <button type='submit'><a href = "{% url 'story6:add_event' %}"> Tambah dulu event nya kosong </a></button>
            {% endif %}
        </tbody>        
    </table>
</section>

{% endblock %}


story9/templates/story9/index.html
{% extends 'story9/base.html' %}

{% block content %}


<div class = "container-sm">
    <div class = "row">
        <div class = "col-md-6">
            <h1 class="wellcom one"> WELCOME, </br>
             </h1>
            {% if user.is_authenticated %}
                <h1 class= "wellcom">  {{ user.username }} </h1>
            <h4 class = "yellow"> Nothing to see? Just <a href ="{% url 'story9:logout' %}" class = "red">Log Out</a> 
            </h4>
            {% else %}
            <h1 class= "wellcom"> (y/n) <h1>
            <h4 class = "yellow"> You are not in the SYSTEM! </br>
            Please<a href ="{% url 'story9:login' %}">  <strong span class="red">  Log In  </strong> </a> with your account!
            </br> Don't have any account? <a href ="{% url 'story9:signup' %}"> <strong span class = "red"> Sign Up </strong></a>now!
            </h4>
        </div>
        
        {% endif %}
    </div>
</div>
{% endblock %}